environments:
  default:
    values:
      - istio:
          enabled: {{ .Values | get "istio.enabled" true }}
---
helmDefaults:
  createNamespace: true

repositories:
  - name: raw
    url: https://bedag.github.io/helm-charts/

releases:
  - name: istio-crds
    namespace: default
    labels:
      package-name: istio-crds
    chart: raw/raw
    version: 2.0.0
    condition: istio.enabled
    values:
      - values/crds.gotmpl
    hooks:
      - events:
          - prepare
        command: bash
        args:
          - "-c"
          - |
            rm -fr values/istio-manifests-crds
            istioctl manifest generate -f istiooperator.yaml | kubectl slice -f - -o values/istio-manifests-crds
      - events:
          - cleanup
        command: bash
        args:
          - -c
          - rm -fr values/istio-manifests-crds

  - name: istio-not-revisioned-resources
    namespace: istio-system
    labels:
      package-name: istio-not-revisioned-resources
    chart: raw/raw
    version: 2.0.0
    condition: istio.enabled
    values:
      - values/not-revisioned-resources.gotmpl
    hooks:
      - events:
          - prepare
        command: bash
        args:
          - "-c"
          - |
            rm -fr values/istio-manifests-not-revisioned-resources
            istioctl manifest generate -f istiooperator.yaml | kubectl slice -f - -o values/istio-manifests-not-revisioned-resources
      - events:
          - cleanup
        command: bash
        args:
          - -c
          - rm -fr values/istio-manifests-not-revisioned-resources

  - name: istio-1-18-5
    namespace: istio-system
    labels:
      package-name: istio
    chart: raw/raw
    version: 2.0.0
    condition: istio.enabled
    needs:
      - default/istio-crds
    values:
      - values/pilot.gotmpl
    disableValidation: true
    hooks:
      - events:
          - prepare
        command: bash
        args:
          - "-c"
          - |
            rm -fr values/istio-manifests-pilot
            istioctl manifest generate -f istiooperator.yaml --component Pilot | kubectl slice -f - -o values/istio-manifests-pilot
      - events:
          - cleanup
        command: bash
        args:
          - -c
          - rm -fr values/istio-manifests-pilot

  - name: istio-ingress-gateways
    namespace: istio-system
    labels:
      package-name: istio-ingress-gateways
    chart: raw/raw
    version: 2.0.0
    condition: istio.enabled
    needs:
      - default/istio-crds
    values:
      - values/ingress.gotmpl
    disableValidation: true
    hooks:
      - events:
          - prepare
        command: bash
        args:
          - "-c"
          - |
            rm -fr values/istio-manifests-ingress
            istioctl manifest generate -f istiooperator.yaml --component IngressGateways | kubectl slice -f - -o values/istio-manifests-ingress
      - events:
          - cleanup
        command: bash
        args:
          - -c
          - rm -fr values/istio-manifests-ingress
